### PR TITLE
More forgiving caching

### LINKED ISSUE #2339: Cache Directory is not configurable
## Intro
When trying to run the `spin` CLI on systems with (mostly) read-only filesystem it is not possible to set the used path for the cache directory.

## Example
When running on a system where only `/tmp` is writeable, doing a `spin up --log-dir "" --runtime-config-file runtime-config.toml --state-dir /tmp`* gives the following error:
```
failed to create manifests directory "/home/<user>/.cache/spin/registry/manifests"
```
*Note: The other flags are set so that `spin` doesn't try to write to other read-only parts of the file system.

## Workaround
There is a workaround though: Setting `XDG_CACHE_HOME`, which gets respected by the used `dirs` crate, to `/tmp` works. 

## Suggestion
Looking through the code it looks like everything is already prepared to set the cache dir (e.g. `Cache::new` already expects an `Option<PathBuf>`) but it doesn't get used anywhere:

`spin up` calls `spin_loader::from_file(&manifest_path, files_mount_strategy, None)` where `None` is the Option to set the cache root.

So my suggestion would be to allow setting the cache root through a `spin` specific environment variable and/or a command line flag.

## More Context
There is a thread about it in the `spin` Discord: https://discord.com/channels/926888690310053918/1215979463918096424

### PR DESCRIPTION
**Pull request by itowlson**
Fixes #2339.

This provides an option to override the registry/download cache directory.  (I've called it download because it's used for more than registry stuff, although that might feel a bit weird on `spin registry push`.  Open to feedback!)

This also creates the cache directory only on demand.  If a problem occurs, the user still finds out about it during startup; but if the cache is never needed, there is no need for the user to cajole Spin into using a better directory.  Note that only the write methods trigger directory creation; "xxx_file" methods already return an error if the path/file doesn't exist, and "xxx_path" methods make it clear that the caller should not assume the path exists.  Still this is an area where reviewer persnicketiness is advised.

The two chunks are separate commits in case we want to take only one of them.

### CODE REVIEW

**Comment by itowlson** [comment]
Okay there is a place (the `verified_download` subsystem) which uses one of the `xxx_path` APIs, then writes to that path without checking that directories exist.  This could be addressed by requiring _everything_ to go through `write_wasm` (which probably means not giving out paths to the unhallowed), or by the point fix of calling `ensure_dirs` on the way into that subsystem.  For the time being, I've adopted the point fix.

File: crates/loader/src/cache.rs [hunk 1]
```diff
@@ -130,12 +141,14 @@ impl Cache {
...
 
+        *self.dirs_ensured.write().await = true;
+
         Ok(())
     }
 }
 
 #[cfg(windows)]
-fn safe_name(digest: impl AsRef<str>) -> impl AsRef<Path> {
+fn safe_name(digest: impl AsRef<str>) -> impl AsRef<std::path::Path> {
```
Comment (itowlson) [inline crates/loader/src/cache.rs:151]: This change occurs because `Path` is now unused except for here.  (I could put a `cfg` on the module level `use` of it, but this seemed less intrusive.)

File: crates/loader/src/cache.rs [hunk 2]
```diff
@@ -17,6 +17,7 @@ const DATA_DIR: &str = "data";
 pub struct Cache {
     /// Root directory for the cache instance.
     root: PathBuf,
+    dirs_ensured: tokio::sync::RwLock<bool>,
```
Comment (rylev) [inline crates/loader/src/cache.rs:20]: Can we use `AtomicBool` instead?

And nit: please add a comment for what this flag is used for

File: src/commands/registry.rs [hunk 3]
```diff
@@ -57,6 +57,10 @@ pub struct Push {
     /// This is a string whose format is defined by the registry standard, and generally consists of <registry>/<username>/<application-name>:<version>. E.g. ghcr.io/ogghead/spin-test-app:0.1.0
     #[clap()]
     pub reference: String,
+
+    /// Cache directory for downloaded registry data.
+    #[clap(long)]
+    pub download_cache_dir: Option<PathBuf>,
```
Comment (rylev) [inline src/commands/registry.rs:63]: Can we just call it `cache_dir` or do we expect have more than one on-disk cache?

File: crates/loader/src/cache.rs (hunk 2 above)
Comment (lann) [reply crates/loader/src/cache.rs:20]: I also like `dirs_ensured_once: tokio::sync::OnceCell<()>`:

https://docs.rs/tokio/1.36.0/tokio/sync/struct.OnceCell.html

```rust
self.dirs_ensured_once.get_or_init(|| async {
    // ensure yer dirs
}).await
```

File: src/commands/registry.rs (hunk 3 above)
Comment (itowlson) [reply src/commands/registry.rs:63]: There is already a `--cache` option for the Wasmtime cache configuration file.  I wanted to distinguish this cache from that.

**Review by fibonacci1729 — APPROVED** [review]
