### PR TITLE
fix: Terminate trigger handler on `spin up` termination

### LINKED ISSUE #638: Integration tests for go sdk does not terminate the spin process
Integration test for Golang starts a spin instance that doesn't get shutdown.

https://github.com/fermyon/spin/blob/main/sdk/go/integration_test.go#L75

### PR DESCRIPTION
**Pull request by lann**
The `Ctrl-C` handler works because it is handled in the trigger handler
child process, but if the parent `spin up` process is terminated
instead - as with e.g. Nomad - the child is left running.

Fix this by adding a signal handler to the parent process which sends
SIGTERM to the child.

I expect this to fix #638

### CODE REVIEW

File: src/commands/up.rs [hunk 1]
```diff
@@ -157,7 +157,20 @@ impl UpCommand {
 
         tracing::trace!("Running trigger executor: {:?}", cmd);
 
-        let status = cmd.status().context("Failed to execute trigger")?;
+        let mut child = cmd.spawn().context("Failed to execute trigger")?;
+
+        #[cfg(not(windows))]
```
Comment (itowlson) [inline src/commands/up.rs:162]: What happens if it is on Windows?

**Comment by fibonacci1729** [comment]
<a href="https://imgflip.com/i/6msmi5"></a><div><a href="https://imgflip.com/memegenerator">from Imgflip Meme Generator</a></div>

File: src/commands/up.rs (hunk 1 above)
Comment (lann) [reply src/commands/up.rs:162]: What happens on windows today? 🤷
