### PR TITLE
Fix watchexec missing files in subdirectories

### LINKED ISSUE #1981: Bug: spin watch broken for nested files
Using spin canary (built from main as of https://github.com/fermyon/spin/commit/47e40b9b38950c55355db575cd1b7ac681292621), I'm seeing behavior where `spin watch` doesn't trigger a rebuild upon changes to nested files.

Any app with a nested file entry in the `watch` config should repro, eg `watch = ["src/**/*.rs", "Cargo.toml"]` as seen in the [http-rust example](https://github.com/fermyon/spin/tree/main/examples/http-rust).  When running this example, a re-build is triggered when the `Cargo.toml` file is amended but not triggered when `src/lib.rs` is amended.

### PR DESCRIPTION
**Pull request by itowlson**
Fixes #1981.

### CODE REVIEW

**Review by radu-matei — APPROVED** [review]

File: src/commands/watch.rs [hunk 1]
```diff
@@ -93,6 +94,7 @@ impl WatchCommand {
 
         let spin_bin = std::env::current_exe()?;
         let manifest_file = spin_common::paths::resolve_manifest_file_path(&self.app_source)?;
+        let manifest_file = manifest_file.absolutize()?.to_path_buf(); // or watchexec misses files in subdirectories
```
Comment (lann) [inline src/commands/watch.rs:97]: BUT WHY

**Review by vdice — APPROVED** [review]

File: src/commands/watch.rs (hunk 1 above)
Comment (itowlson) [reply src/commands/watch.rs:97]: BECAUSE REASONS LANN REASONS

We could probably absolutise at the last moment before we pass the directory to `watchexec` - I just get paranoid about capturing the true location as early as possible (a) so I don't need to remember to do it at _all_ the last moments and (b) in case some other piece of code sneakily switches out the current directory from underneath me.  _thousand yard stare_

We can iterate on this for sure though.
