### PR TITLE
`spin plugins install` without version: install latest compatible not latest ever

### LINKED ISSUE #1661: `spin plugin install` fails if latest plugin version doesn't support current Spin version
on trying to install the plugins with spin 1.3, we get following error:

```
$) spin --version
spin 1.3.0 (9fb8256 2023-06-12)

$) spin plugin install js2wasm --yes

Error: Plugin is not compatible with this version of Spin (supported: >=1.4, actual: 1.3.0). Try running `spin plugins update && spin plugins upgrade --all` to install latest or override with `--override-compatibility-check`.
```

It seems because the latest release of js2wasm plugin has compatibility with spin version `>=1.4` only.

It might be useful to identify and install the `latest compatible` version automatically rather than failing the installation.

### PR DESCRIPTION
**Pull request by itowlson**
Fixes #1661 and #1548.

### CODE REVIEW

File: crates/plugins/src/lookup.rs [hunk 1]
```diff
@@ -41,37 +72,74 @@ impl PluginLookup {
...
+                    Some(self.name.clone()),
+                    expected_path.display().to_string(),
+                    e.to_string(),
+                ))
+            }),
+            Err(e) if e.kind() == std::io::ErrorKind::NotFound && self.version.is_some() => {
+                // If a user has asked for a version by number, and the path doesn't exist,
+                // it _might_ be because it's the latest version. This checks for that case.
+                let latest = Self::new(&self.name, None);
+                if let Ok(manifest) = latest.resolve_manifest_exact_from_good_repo(plugins_dir) {
```
Comment (rajatjindal) [inline crates/plugins/src/lookup.rs:108]: should we assert for the version number here (to ensure latest-version == version-requested)?

Comment (itowlson) [reply crates/plugins/src/lookup.rs:108]: Oops, yes, I think we should.  I did a lengthy series of refactorings on this mess and lost it along the way.  Thank you!

File: crates/plugins/src/lookup.rs [hunk 2]
```diff
@@ -30,7 +30,38 @@ impl PluginLookup {
...
+            let store = crate::store::PluginStore::new(plugins_dir.to_owned());
+
+            // This is very similar to some logic in the badger module
+            let manifests = store.catalogue_manifests()?;
+            let relevant_manifests = manifests.into_iter().filter(|m| m.name() == self.name);
+            let compatible_manifests = relevant_manifests.filter(|m| {
+                m.has_compatible_package() && m.is_compatible_spin_version(spin_version)
+            });
+            let highest_compatible_manifest =
+                compatible_manifests.max_by_key(|m| semver::Version::parse(&m.version).unwrap());
```
Comment (rylev) [inline crates/plugins/src/lookup.rs:55]: Is unwrapping the right thing to do here? Can we do `unwrap_or_else(|| semver::Version::new(0,0,0))`?

File: crates/plugins/src/lookup.rs [hunk 3]
```diff
@@ -30,7 +30,38 @@ impl PluginLookup {
...
+
+            match highest_compatible_manifest {
+                Some(m) => Ok(m),
+                None => Ok(exact), // We can't do any better than latest after all
+            }
```
Comment (rylev) [inline crates/plugins/src/lookup.rs:60]:
```suggestion
           Ok(highest_compatible_manifest.unwrap_or(exact))
```

File: crates/plugins/src/lookup.rs [hunk 4]
```diff
@@ -41,37 +72,78 @@ impl PluginLookup {
...
                 Some(self.name.clone()),
                 expected_path.display().to_string(),
                 e.to_string(),
-            ))
-        })?;
-        Ok(manifest)
+            )))
+        };
+
+        let manifest = match File::open(&expected_path) {
```
Comment (rylev) [inline crates/plugins/src/lookup.rs:96]: Doing I/O in async is usually a no/no. It's fine here though I suppose.

File: crates/plugins/src/lookup.rs [hunk 5]
```diff
@@ -41,37 +72,78 @@ impl PluginLookup {
...
+                    Some(self.name.clone()),
+                    expected_path.display().to_string(),
+                    e.to_string(),
+                ))
+            }),
+            Err(e) if e.kind() == std::io::ErrorKind::NotFound && self.version.is_some() => {
+                // If a user has asked for a version by number, and the path doesn't exist,
+                // it _might_ be because it's the latest version. This checks for that case.
+                let latest = Self::new(&self.name, None);
+                if let Ok(manifest) = latest.resolve_manifest_exact_from_good_repo(plugins_dir) {
```
Comment (rylev) [inline crates/plugins/src/lookup.rs:108]: Can this be refactored into a `match` with two patterns:

```rust
match latest.resolve_manifest_exact_from_good_repo(plugins_dir) {
  Ok(manifest) if semver::Version::parse(manifest.version()).ok() == self.version => Ok(manifest),
  _ => not_found(e)
}

Comment (itowlson) [reply crates/plugins/src/lookup.rs:108]: aha, yes, I was sure this could be simplified and this is the way - thanks!

File: crates/plugins/src/error.rs [hunk 6]
```diff
@@ -14,6 +14,9 @@ pub enum Error {
 
     #[error("URL parse error {0}")]
     UrlParseError(#[from] url::ParseError),
+
+    #[error("{0}")]
+    Other(#[from] anyhow::Error),
```
[the remark this answers is not in the document]
Comment (itowlson) [reply crates/plugins/src/error.rs:19]: I tried this but it gives

```
`?` couldn't convert the error to `error::Error`
the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
the trait `From<url::ParseError>` is implemented for `error::Error`
required for `Result<PluginManifest, error::Error>` to implement `FromResidual<Result<Infallible, anyhow::Error>>`
```

so keeping it as is

**Review by rajatjindal — APPROVED** [review]

**Review by kate-goldenring — APPROVED** [review]

**Comment by rajatjindal** [comment]
Hi @itowlson can we backport this to 1.3.x?
