### PR TITLE
Fix issues with publishing or consuming registries on Windows

### LINKED ISSUE #2829: Static assests like CSS and JS are not coming properly for SPIN application after deploying to cloud
Do any of the following links help with your problem?

[Application Prerequisites](https://developer.fermyon.com/spin/build#setting-up-for-spin-build)
Spin Build and Spin Up is Working
[Troubleshooting - Rust](https://developer.fermyon.com/spin/rust-components#troubleshooting)
NA
[Cloud FAQ](https://developer.fermyon.com/cloud/faq)
NA

If you still see a bug or problem, please let us know:

I have setup demo project here https://github.com/kunjee17/spin_cloud_test . Basically everything works without any issue. Even spin build and spin up also works. But as they say `it works on my machine` . When I deployed the application https://pi-health.fermyon.app/ html works but it looses css and js files. I did try to trouble shoot it, but unlike normal server I don't if that is possible to get into WASM to see if all files are there. More frustrating is that it works locally.  Do let me know if any other thing is required from my end. 

* Spin version (`spin --version`) spin 2.7.0 (a111517 2024-07-30)
* Installed plugin versions (`spin plugins list --installed`)
```
cloud 0.9.1 [installed]
js2wasm 0.6.1 [installed]
```

### PR DESCRIPTION
**Pull request by itowlson**
Fixes #2829.  This PR forces all asset paths in the registry lockfile to be forward-slash format, which works on both Windows and Unix.

This also fixes an issue found during testing, where running from a local registry failed with a cryptic error, because the port separator is an illegal character in a Windows file name.

### CODE REVIEW

**Comment by itowlson** [comment]
To clarify: this should fix the original issue _when incorporated into `cloud-plugin`,_ although I haven't tested it in the cloud scenario yet.

**Review by rylev — APPROVED** [review]

File: crates/oci/src/client.rs [hunk 1]
```diff
@@ -782,6 +786,41 @@ fn add_inferred(map: &mut BTreeMap<String, String>, key: &str, value: Option<Str
...
+#[cfg(not(target_os = "windows"))]
+fn portable_path(rel_path: &Path) -> PathBuf {
+    rel_path.into()
+}
+
+/// Takes a string intended for use as part of a path and makes it
+/// compatible with the local filesystem.
+#[cfg(target_os = "windows")]
+fn fs_safe_segment(segment: &str) -> impl AsRef<Path> {
+    segment.replace(':', "_")
```
Comment (lann) [inline crates/oci/src/client.rs:813]: I think it would be fine to replace this unconditionally :shrug:

**Review by vdice — APPROVED** [review]

**Review by kate-goldenring — APPROVED** [review]
