### PR TITLE
Install templates from remote tarball

### LINKED ISSUE #2955: Install templates from a remote tarball
Broken out from #2555 @jandubois: 

> **There is no way to install templates from a remote tarball**
>
> Since we [sc. Rancher Desktop] can't rely on git being installed, we need to install using `--dir` from a local directory because there is no option to install from a remote tarball like this:
>
> `spin templates install --from https://github.com/fermyon/spin/archive/refs/heads/main.tar.gz`
>
> That means we need to download the file ourselves, unpack it into a temporary directory, install from there, and then remove the temporary directory again.
>
> Since we are doing this from a shell script, it means we need curl or wget, neither of which are guaranteed to be installed.

### PR DESCRIPTION
**Pull request by itowlson**
Fixes #2955.

```
$ rm -rf ~/.local/share/spin/templates/
$ spin templates install --tar https://github.com/fermyon/spin/archive/refs/tags/v3.0.0.tar.gz
Copying remote template source
Installing template http-go...
Installing template redis-go...
Installing template http-grain...
Installing template http-empty...
Installing template redis-rust...
Installing template static-fileserver...
Installing template http-rust...
Installing template http-zig...
Installing template redirect...
Installing template http-c...
Installing template http-php...
Installed 11 template(s)

+------------------------------------------------------------------------+
| Name                Description                                        |
+========================================================================+
| http-c              HTTP request handler using C and the Zig toolchain |
| http-empty          HTTP application with no components                |
| http-go             HTTP request handler using (Tiny)Go                |
| http-grain          HTTP request handler using Grain                   |
| http-php            HTTP request handler using PHP                     |
| http-rust           HTTP request handler using Rust                    |
| http-zig            HTTP request handler using Zig                     |
| redirect            Redirects a HTTP route                             |
| redis-go            Redis message handler using (Tiny)Go               |
| redis-rust          Redis message handler using Rust                   |
| static-fileserver   Serves static files from an asset directory        |
+------------------------------------------------------------------------+
```

### CODE REVIEW

File: crates/templates/src/source.rs [hunk 1]
```diff
@@ -192,6 +203,84 @@ async fn check_local(path: &Path) -> anyhow::Result<LocalTemplateSource> {
...
+
+    Ok(LocalTemplateSource {
+        root: templates_root,
+        _temp_dir: Some(temp_dir),
+    })
+}
+
+fn bypass_gh_added_root(unpack_dir: PathBuf) -> PathBuf {
+    // GitHub adds a prefix directory to release tarballs (e.g. spin-v3.0.0/...).
+    // We try to locate the repo root within the unpacked tarball.
```
Comment (rylev) [inline crates/templates/src/source.rs:236]: Nit: any reason to not make this a doc comment on the function so that this surfaces more easily when code spelunking?

File: src/commands/templates.rs [hunk 2]
```diff
@@ -119,15 +131,19 @@ impl Install {
...
-            (None, Some(dir)) => {
+            (None, Some(dir), None) => {
                 let abs_dir = dir.absolutize().map(|d| d.to_path_buf());
                 TemplateSource::File(abs_dir.unwrap_or_else(|_| dir.clone()))
             }
+            (None, None, Some(tar_url)) => {
+                let url = url::Url::parse(tar_url).context("Invalid URL for remote tar")?;
+                TemplateSource::RemoteTar(url)
+            }
             _ => anyhow::bail!("Exactly one of `git` and `dir` sources must be specified"),
```
Comment (rylev) [inline src/commands/templates.rs:147]: This error should be updated to reflect the third option

File: crates/templates/src/source.rs [hunk 3]
```diff
@@ -192,6 +203,84 @@ async fn check_local(path: &Path) -> anyhow::Result<LocalTemplateSource> {
     }
 }
 
+async fn download_untar_local(url: &Url) -> anyhow::Result<LocalTemplateSource> {
```
Comment (rylev) [inline crates/templates/src/source.rs:206]: Would this make sense as a function on `LocalTemplateSource`? Like `LocalTemplateSource::from_remote_tarball`? Then you can leave a doc comment outlining that it downloads the tarball to a temp dir.

**Review by rylev — APPROVED** [review]
I have some nits that I'd love to see addressed, but nothing is blocking.

File: crates/templates/src/source.rs (hunk 3 above)
Comment (itowlson) [reply crates/templates/src/source.rs:206]: The other "pull down a remote source" functions are free, so I've followed the same pattern for now.  We can change them all to methods in a separate refactoring pass if we prefer that.  In the meantime I've added the doc comment.
