### PR TITLE
Check for illegal file name when copying single file

### LINKED ISSUE #2361: In `component.files`, mapping a single file to `/` gives an unhelpful error
The `component.files` section allows a directory or file to be mounted in the guest at a specific location, e.g. `{ source = "cat.jpg", destination = "/dog.jpg" }`.

If the destination is an illegal name for a file, such as `/`, an error occurs, but does not clearly point to the problem:

```
Error: Failed to load manifest from "spin.toml"

Caused by:
   0: Failed to load Spin app from "spin.toml"
   1: Failed to load component `favicon`
   2: Failed to copy "/Users/vdice/code/github.com/benwis/benwis_spin/target/site/favicon.ico" to "/private/var/folders/nc/yfj0pylx4vzdr3s_66r129s00000gn/T/spinup-vQC7kb/assets/favicon/"
   3: No such file or directory (os error 2)
```

It should say something like "`/` is not a valid destination file name."

### PR DESCRIPTION
**Pull request by itowlson**
Fixes #2361.

Example output:

```
$ spin up -f ./crates/loader/tests/file-errors/bad.toml 
Error: Failed to load manifest from "./crates/loader/tests/file-errors/bad.toml"

Caused by:
   0: Failed to load Spin app from "./crates/loader/tests/file-errors/bad.toml"
   1: Failed to load component `bad`
   2: Failed to copy "/home/ivan/github/spin/crates/loader/tests/file-errors/host.txt" to working path "/tmp/spinup-x8yn3O/assets/bad/": "/" is not a valid destination file name
```

### CODE REVIEW

File: crates/loader/src/local.rs [hunk 1]
```diff
@@ -394,17 +397,40 @@ impl LocalLoader {
...
+    ) -> anyhow::Result<T> {
+        let src_text = quoted_path(src);
+        let dest_text = quoted_path(dest);
+        let base_msg = format!("Failed to copy {src_text} to working path {dest_text}");
+
+        if let Some(io_error) = e.downcast_ref::<std::io::Error>() {
+            if Self::is_directory_like(guest_dest)
+                || io_error.kind() == std::io::ErrorKind::NotFound
+            {
+                bail!("{base_msg}: \"{guest_dest}\" is not a valid destination file name");
```
Comment (rylev) [inline crates/loader/src/local.rs:421]: nit: could we make everything after the `base_msg` into another error (perhaps by using `with_context`) so that that information shows up on a different line when displaying the full error. As it is right now, this error message is very long.

Comment (itowlson) [reply crates/loader/src/local.rs]: Good call.  I broke the message up and it now looks like:

```
$ spin up -f ./crates/loader/tests/file-errors/bad.toml 
Error: Failed to load manifest from "./crates/loader/tests/file-errors/bad.toml"

Caused by:
   0: Failed to load Spin app from "./crates/loader/tests/file-errors/bad.toml"
   1: Failed to load component `bad`
   2: Failed to copy "/home/ivan/github/spin/crates/loader/tests/file-errors/host.txt" to working path "/tmp/spinup-iloZyr/assets/bad/"
   3: "/" is not a valid destination file name
```

which draws out the underlying error much more clearly.  Thanks!
