### PR TITLE
Mostly flagless app source

### LINKED ISSUE #1155: Flagless `spin up` application source
Instead of having to write `spin up -f ~/myapp/spin.toml` or `spin up --from-registry ghcr/me/myapp:v1`, the user should be allowed to write:

* `spin up ~/myapp/spin.toml` - Spin detects it's a file and runs it
* `spin up ~/myapp` - Spin detects that it's a directory and, if it contains a file named `spin.toml`, runs it
* `spin up ghcr.io/me/myapp:v1` - Spin detects that it's not a file and "looks like" a registry URI, tries to pull the artifact using the OCI protocol, and runs it if successful

The strategy will work like this:

* If no application source if specified:
  * If the current directory contains a file with the default manifest name, use it
  * Otherwise, display help
* If an application source string is specified, try to access the string as a file system reference.
  * If it exists and is a file, use it
  * If it exists and is a directory:
    * If it contains a file with the default manifest name, use that
    * Otherwise, fail with a "directory doesn't contain a manifest" error
  * If it doesn't exist, or isn't a legal filename, try to parse it as a registry reference _[to do: consider heuristic checks first, TBD]_
    * If the parse succeeds, try to pull from the reference (respecting cache etc.)
      * If the pull succeeds, run the artifact.  _(In future, if there are multiple registry protocols with "similar looking" references, this could be elaborated with e.g. check for well-known servers of different types, fail over to the other type, etc.)_
      * If pull fails, fail with a registry error
    * If the parse fails, fail with a "don't understand this source" error

The error messages alone will be glorious.

There should also be a flag that the user can set to force a specific interpretation of the source string e.g. `--source-type file`, `source-type oci`.  The default will be `--source-type auto` which tells Spin to use the strategy given above.

As we are aiming to move from Bindle to OCI, this will not support bindle IDs.  For the time being, the existing bindle-related flags will remain available to support this scenario.

### PR DESCRIPTION
**Pull request by itowlson**
Fixes #1155.

This is similar to #1159 but compromises on total flaglessness to make it play nicely with trigger options.  With this, you still have to write `-f` for anything other than the default source (current directory + spin.toml), but you don't need to write `--from-file` or `--from-registry` unless the "inference engine" gets it wrong.  E.g.

```
# Infers: File: ./spin.toml
spin up

# Infers: File: ./app.toml
spin up -f app.toml

# Infers: File: ./guest/spin.toml
spin up -f guest

# Infers: Registry: ghcr.io/test/myapp:v1
spin up -f ghcr.io/test/myapp:v1
```

Error cases:

```
# If not a file/directory
$ spin up -f guest2
Error: File or directory 'guest2' not found. If you meant to load from a registry, use the `--from-registry` option.

# If not a file/directory, *but* something that looks like a tag is present
$ spin up -f guest2/bish/bosh:v1
Error: cannot pull Spin application from registry

Caused by:
    Not authorized: url https://index.docker.io/v2/guest2/bish/bosh/manifests/v1
```

The following tweaks are also made to the `spin up` UI:
* Bindle flags are hidden but continue to work (no deprecation warning is issued)
* The `from-bindle` alias is added despite this, because consistency even on the edge of the pit
* `--file` is moved to an alias but continues to be supported

There should be no breaking change for the `-f` flag, except that if it is pointed at a non-existent file, it _may_ now fail with a registry error instead of a file not found error.

**NOTE:** this currently has the full, tragic commit history of the flagless work; if we decide to adopt it, then this should be squashed before merging.

### CODE REVIEW

**Comment by itowlson** [comment]
I would _really really_ appreciate it if someone with access to some more realistic registry references could test this - I have been testing with one of Brian's that I don't have access to and confirmed that it gives a suitable OCI error, but it would be good to get more variation especially since the reference parsing involves heuristics.

(Hark at me, first inference engine and now heuristics!  It's a couple of `if` expressions Ivan, don't gussy it up all fancy on them.)

**Comment by itowlson** [comment]
Found a regression where `spin up <file>` (note without the `-f`) now gives trigger options help instead of `Cannot read manifest file from "/home/ivan/spinbin/spin.toml"`.

**Comment by itowlson** [comment]
At least, a regression in the sense of "both are bad but it is a different bad."  Displaying help text is arguably less surprising than firing up the app in the current directory when you thought you'd asked for a different one!

But now we're back to the positional trigger args problem: there's no definite way to distinguish `spin up foo` (wrong, meant to pass `-f`) from `spin up foo` (right, passing `foo` to the trigger)...

**Comment by itowlson** [comment]
To clarify, this only happens if `./spin.toml` doesn't exist.  If It does exist, the current behaviour is to print:

```
error: Found argument 'foo' which wasn't expected, or isn't valid in this context

USAGE:
    spin trigger http [OPTIONS]

For more information try --help
```

and this PR does not change that WHEEEE

**Comment by itowlson** [comment]
I piled on another heuristic to handle the `spin up foo` case:

```
$ spin up examples/http-rust
Error: Default file 'spin.toml' found. Did you mean `spin up -f examples/http-rust`?`

$ spin up --listen 127.0.0.1:4000
Serving http://127.0.0.1:4000
```

With this sort of hack we could go back to the fully flagless design, though at least in this one the hack is controlling only the failure mode rather than the interpretation of the application source.

**Comment by radu-matei** [comment]
I'm passing the `-f` and `--from-registry` flags to the same registry app:

```
❯ spin up --listen 127.0.0.1:3003  --from-registry ghcr.io/radu-matei/hello-registries:v1
2023-02-22T10:11:09.247402Z TRACE spin_cli::commands::up: Running trigger executor: "/Users/radu/projects/src/github.com/fermyon/spin/target/release/spin" "trigger" "http" "--listen" "127.0.0.1:3003" "--from-registry"
2023-02-22T10:11:09.272781Z DEBUG spin_loader::oci::cache: using cache root directory /Users/radu/Library/Caches/spin/registry
2023-02-22T10:11:09.289584Z TRACE spin_http: Constructed router for application hello-registries: {Wildcard(""): "hello-registries"}
Serving http://127.0.0.1:3003
2023-02-22T10:11:09.289679Z  INFO spin_http: Serving http://127.0.0.1:3003
Available Routes:
  hello-registries: http://127.0.0.1:3003 (wildcard)


❯ spin up --listen 127.0.0.1:3003  -f ghcr.io/radu-matei/hello-registries:v1
2023-02-22T10:11:51.056584Z DEBUG spin_loader::oci::cache: using cache root directory /Users/radu/Library/Caches/spin/registry
2023-02-22T10:11:52.482909Z TRACE spin_cli::commands::up: Running trigger executor: "/Users/radu/projects/src/github.com/fermyon/spin/target/release/spin" "trigger" "http" "--listen" "127.0.0.1:3003"
Error: loader error: LockedComponentSource missing source field

Caused by:
    LockedComponentSource missing source field
Error: exit status: 1
```

File: src/commands/up.rs [hunk 1]
```diff
@@ -280,7 +388,7 @@ impl UpCommand {
         let exec_opts = if self.help {
             TriggerExecOpts::NoApp
         } else {
-            let from_registry = self.reference.is_some();
+            let from_registry = self.registry_source.is_some();
```
Comment (fibonacci1729) [inline src/commands/up.rs:391]: @itowlson Because this isn't necessarily set for a registry reference (e.g. `-f ghcr.io/alice/foobar:v1`) the trigger flag `--from-registry` will not properly be set when inferring an OCI reference from `-f` as the `AppSource`.

I'd suggest changing `prepare_locked_app` to explicitly accept a `from_registry: bool` parameter that is `true` when calling from `prepare_app_from_oci` and `false` for `prepare_app_from_bindle`.

**Comment by itowlson** [comment]
Yikes, thanks to both of you for the catch!

It would be _super duper useful_ if we had a publicly accessible demo that could be used for testing OCI bits.  Or is there one in the e2e tests somewhere?

**Comment by itowlson** [comment]
I think this is now fixed:

```
# Inference
$ spin up -f localhost:5000/itowlson/http-rust:1 --insecure
Serving http://127.0.0.1:3000
Available Routes:
  hello: http://127.0.0.1:3000/hello
    A simple component that returns hello.

$ spin up -f ./examples/http-rust
Serving http://127.0.0.1:3000
Available Routes:
  hello: http://127.0.0.1:3000/hello
    A simple component that returns hello.

$ spin up -f ./examples/http-rust/spin.toml 
Serving http://127.0.0.1:3000
Available Routes:
  hello: http://127.0.0.1:3000/hello
    A simple component that returns hello.

# Forcing flags
$ spin up --from-registry localhost:5000/itowlson/http-rust:1 --insecure
Serving http://127.0.0.1:3000
Available Routes:
  hello: http://127.0.0.1:3000/hello
    A simple component that returns hello.

$ spin up --bindle spin-hello-world/1.0.0 --bindle-server http://localhost:8080/v1 --insecure
Serving http://127.0.0.1:3000
Available Routes:
  hello: http://127.0.0.1:3000/hello
    A simple component that returns hello.

$ spin up --from-file ./examples/http-rust
Serving http://127.0.0.1:3000
Available Routes:
  hello: http://127.0.0.1:3000/hello
    A simple component that returns hello.
```

(I clicked through all of them too to make sure they worked, but will save you the log spew.)

Thanks to @vdice for help getting a working registry and @fibonacci1729 for volunteering his app as tribute.

**Comment by itowlson** [comment]
Marking this as ready for review since people are testing it enough to imply this is the direction we want to go...?

**Comment by radu-matei** [comment]
`ghcr.io/radu-matei/cloud-start:v1` should be public, so you could try with this one: https://github.com/users/radu-matei/packages/container/package/cloud-start

Alternatively, you could push an app to GHCR as well.

**Review by fibonacci1729 — APPROVED** [review]
I gave this another round of testing this morning and the code looks reasonable to me! LGTM.

File: src/commands/up.rs [hunk 2]
```diff
@@ -134,13 +159,102 @@ impl UpCommand {
...
+            &self.file_source,
+            &self.bindle_source,
+            &self.registry_source,
+        ) {
+            (None, None, None, None) => self.default_manifest_or_none(),
+            (Some(source), None, None, None) => Self::infer_source(source),
+            (None, Some(file), None, None) => Self::infer_file_source(file.to_owned()),
+            (None, None, Some(id), None) => AppSource::Bindle(id.to_owned()),
+            (None, None, None, Some(reference)) => AppSource::OciRegistry(reference.to_owned()),
+            (_, _, _, _) => AppSource::unresolvable("More than one application was specified"),
```
Comment (dicej) [inline src/commands/up.rs:174]: Entirely optional slight simplification:
```suggestion
            _ => AppSource::unresolvable("More than one application was specified"),
```

**Review by dicej — APPROVED** [review]
Thanks for doing this (and saving the rest of us from having to)!

File: src/commands/up.rs (hunk 2 above)
Comment (itowlson) [reply src/commands/up.rs:174]: Obvious in retrospect but TIL - thank you.

**Comment by kate-goldenring** [comment]
Haven't looked over the implementation yet but the ux was great. Worked with oci images, local files and folders, and with bindle (`./target/debug/spin up --from-bindle spin-hello-world/1.0.0 --bindle-server http://127.0.0.1:8081/v1`)!
