### PR TITLE
Fix Postgres NULL attempting type conversion

### LINKED ISSUE #1808: WrongType error when inserting NULL into VARCHAR nullable column
**Spin version**: spin 1.5.0 (ca08dd9 2023-09-13); **NO** plugins installed

I'm trying to insert NULL into column with type VARCHAR, like this:

```rust
pg::query(
    ADDRESS,
    "INSERT INTO names (name) VALUES ($1)",
    &vec![ParameterValue::DbNull],
)?;
```

It doesn't work, I'm getting error:

```
Error { kind: ToSql(0), cause: Some(WrongType { postgres: Varchar, rust: "core::option::Option<i32>" }) }
```

It does not work for any type except INT4.

## sample app

database schema:

```sql
CREATE TABLE names (name VARCHAR);
```

spin component sources:

```rust
use anyhow::Result;
use spin_sdk::{
    http::{Request, Response},
    http_component,
    pg::{self, ParameterValue},
};

const ADDRESS: &str = "postgres://postgres@localhost:5432/testdb";

/// A simple Spin HTTP component.
#[http_component]
fn handle_test_pg2(_req: Request) -> Result<Response> {
    pg::query(
        ADDRESS,
        "INSERT INTO names (name) VALUES ($1) RETURNING name",
        &vec![ParameterValue::DbNull],
    )?;

    Ok(http::Response::builder()
        .status(200)
        .header("foo", "bar")
        .body(Some("Hello, Fermyon".into()))?)
}
```

### PR DESCRIPTION
**Pull request by itowlson**
Fixes #1808.

The underlying issue is that, while the Rust Postgres driver does map `Option::None` to database `NULL`, it still cares about the _type_ of the `None`.  This replaces the typeful `None` with a custom value that tells the driver to send it as NULL no matter what.

### CODE REVIEW

File: crates/outbound-pg/src/lib.rs [hunk 1]
```diff
@@ -285,3 +283,40 @@ where
         }
     });
 }
+
+struct PgNull;
```
Comment (rylev) [inline crates/outbound-pg/src/lib.rs:287]: Can you add doc comments to this type explaining exactly what you explain in the PR description?

File: crates/outbound-pg/src/lib.rs [hunk 2]
```diff
@@ -285,3 +283,40 @@ where
...
+
+impl ToSql for PgNull {
+    fn to_sql(
+        &self,
+        _ty: &Type,
+        _out: &mut tokio_postgres::types::private::BytesMut,
+    ) -> std::result::Result<tokio_postgres::types::IsNull, Box<dyn std::error::Error + Sync + Send>>
```
Comment (rylev) [inline crates/outbound-pg/src/lib.rs:294]:
```suggestion
    ) -> Result<tokio_postgres::types::IsNull, Box<dyn std::error::Error + Sync + Send>>
```

**Review by rylev — CHANGES_REQUESTED** [review]

**Review by rylev — APPROVED** [review]
🎉
