### PR TITLE
fix(build): Remove git worktree requirements for build to succeed

### LINKED ISSUE #1589: Cannot Build Spin from Released Source Code
Building Spin from a Spin release source code fails for all releases from v1.2.0 and onwards due to required Git information needed in `build.rs`:

```rs
fn main() {
    vergen::EmitBuilder::builder()
        .build_date()
        .build_timestamp()
        .cargo_target_triple()
        .cargo_debug()
        .git_branch()
        .git_commit_date()
        .git_commit_timestamp()
        .git_sha(true)
        .fail_on_error()
        .emit()
        .expect("failed to extract build information");
...
```

This was added in https://github.com/fermyon/spin/pull/1492/files in order to populate more information to plugins. We should set empty defaults for these values if the do not exist.

## To repro

```sh
curl -LRO https://github.com/fermyon/spin/archive/refs/tags/v1.3.0.tar.gz
tar -xvf v1.3.0.tar.gz
cd spin-1.3.0
cargo build
```
Output

```sh
error: failed to run custom build command for `spin-cli v1.3.0 (/Users/kagold/Programs/temp/spin-1.3.0)`

Caused by:
  process didn't exit successfully: `/Users/kagold/Programs/temp/spin-1.3.0/target/release/build/spin-cli-022ecc32c217a5a5/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'failed to extract build information: not within a suitable 'git' worktree!', build.rs:28:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `spin-cli v1.3.0 (/Users/kagold/Programs/temp/spin-1.3.0)`, intermediate artifacts can be found at `/Users/kagold/Programs/temp/spin-1.3.0/target`
```

### PR DESCRIPTION
**Pull request by kate-goldenring**
fixes #1589

The git environment variables passed to plugins will be set to [`vergen`'s defaults](https://github.com/rustyhorde/vergen/blob/8e0f393f59696b68b533e2fc94eba22ff7c2e377/vergen/src/feature/git/gix.rs#L244) if Spin is being built from source code rather than a git environment.

Aside: The fact that the Rust SDK was preventing successful builds of Spin provides impetus for maybe moving the SDKs to their own repositories

### CODE REVIEW

File: sdk/rust/build.rs [hunk 1]
```diff
@@ -17,7 +17,7 @@ fn main() {
     let commit = if output.status.success() {
         String::from_utf8(output.stdout).unwrap()
     } else {
```
Comment (endocrimes) [inline sdk/rust/build.rs:19]: Can't comment on the correct line, but if git isn't installed I think line 15 will fail if `git` isn't available in your PATH

File: sdk/rust/build.rs [hunk 2]
```diff
@@ -8,16 +8,19 @@ fn main() {
...
+                String::from_utf8(output.stdout).unwrap()
+            } else {
+                // Spin is not a part of a Git worktree
+                String::from("unknown")
+            }
+        }
+        Err(_e) => {
+            // Git is not installed
+            String::from("unknown")
+        }
```
Comment (rylev) [inline sdk/rust/build.rs:23]:
```suggestion
let commit = Command::new("git")
        .arg("rev-parse")
        .arg("HEAD")
        .output()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(output.stdout))
        .unwrap_or("unknown");
   
```

Comment (kate-goldenring) [reply sdk/rust/build.rs:23]: Thanks @rylev. This is much more concise! I slightly modified the mapping to first map `Result<Output, Error>` to an option.

File: sdk/rust/build.rs [hunk 3]
```diff
@@ -8,17 +8,14 @@ fn main() {
         format!("-{pre}")
     };
 
-    let output = Command::new("git")
+    let commit: String = Command::new("git")
```
Comment (rylev) [inline sdk/rust/build.rs:11]: Nit: is there any reason for the `: String` annotation?

Comment (kate-goldenring) [reply sdk/rust/build.rs:11]: No. Thanks for pointing it out. it was remnant from me playing around with the mapping.

**Review by rylev — APPROVED** [review]
