### PR TITLE
Munge Spin app name to legal bindle name

### LINKED ISSUE #916: `spin deploy` fails if the application name contains ` `[space]
Examples spin.tom;

```
    spin_version = "1"
    authors = ["Fermyon Engineering <engineering@fermyon.com>"]
    name = "WorldCup Slack Bot"
    trigger = { type = "http", base = "/" }
    version = "1.0.0"
    
    [[component]]
    id = "botapi"
    source = "target/wc-bot.wasm"
    allowed_http_hosts = ["https://worldcupjson.net"]
    [component.trigger]
    route = "/"
    [component.build]
    command = "npm run build"
```

`spin build` and `spin up` works.

`spin deploy`

```
Uploading WorldCup Slack Bot version 1.0.0+r179b90f6...
Error: Failed to push bindle WorldCup Slack Bot/1.0.0+r179b90f6 to server https://cloud.fermyon.com/api/registry

Learn more at https://developer.fermyon.com/cloud/faq
```

Related to #504

### PR DESCRIPTION
**Pull request by itowlson**
Fixes #916.

```
ivan@hecate:~/testing/This_Has_Spaces_In_It$ cat spin.toml
spin_version = "1"
name = "This Has Spaces In It"
trigger = { type = "http", base = "/" }
version = "0.1.0"
# component omitted

ivan@hecate:~/testing/This_Has_Spaces_In_It$ spin deploy
Uploading This_Has_Spaces_In_It version 0.1.0+r84c38c28...
Deploying...
Waiting for application to become ready....... ready
Available Routes:
  this-has-spaces-in-it: https://this-has-spaces-in-it-s1b76abe.fermyon.app (wildcard)
```

@bacongobbler I'd value your thoughts on whether this is the right place to do this and on whether we need to find a munging strategy that can't produce collisions - thanks!  Also, per the Bindle spec, I'm currently letting through non-ANSI letters and numbers, but not sure if those will cause an issue for the sub-domain...

Signed-off-by: itowlson <ivan.towlson@fermyon.com>

### CODE REVIEW

**Comment by itowlson** [comment]
Huh, our integration tests use `-` quite extensively even though it's formally not permitted by the Bindle naming specification.  I'll make this more forgiving for now, then we can discuss whether we want to keep existing hyphen behaviour, or be strict and change the tests accordingly..

File: crates/publish/src/expander.rs [hunk 1]
```diff
@@ -370,13 +370,26 @@ fn bindle_id(
...
 
+// This is both slightly conservative and slightly loose. According to the spec,
+// the / character should also be allowed, but currently that is not supported
+// by Hippo (Spin issue 504). And the - character should not be allowed, but lots of
+// our tests use it...!
+lazy_static::lazy_static! {
+    static ref UNSAFE_CHARACTERS: regex::Regex = regex::Regex::new("[^-_\\p{L}\\p{N}]").expect("Invalid name regex");
+}
+
+fn safe_bindle_name(name: &str) -> String {
```
Comment (michelleN) [inline crates/publish/src/expander.rs:389]: I think it might be easier both from a codebase upkeep perspective and to understand for the end user if we rejected unsafe names rather than transforming them into safe names. What do you think @itowlson ? Are there other reasons for transforming the name on behalf of the user?

Comment (itowlson) [reply crates/publish/src/expander.rs:389]: Sure!  I'll make that change - thanks.

**Review by bacongobbler — APPROVED** [review]
