### PR TITLE
Fix `spin up --help` omitting many options if app is not ready to lock

### LINKED ISSUE #932: `spin up --help` doesn't display all options unless application is fully ready to load
If I do a `spin up --help` in a directory with a `spin.toml`, I normally get a full set of options including those that (internally) happen to be implemented through the trigger such as `--log-dir` and `--follow`.

However, if I `spin new` a directory and do `spin up --help`, I get only the subset that (internally) happen to be implemented diirectly on the `Up` command type itself.

But if I do a `spin build` then it starts working again.  It was the inability to load the component Wasm source that was causing the options to disappear.

So it looks like `spin up --help` is trying to load the application to the point where it is ready for the relevant `spin trigger foo` command to execute, even though all we actually need to be able to extract is the trigger type.

### PR DESCRIPTION
**Pull request by itowlson**
Partially fixes #932.

There remains an outstanding issue where `spin up --help` will skip "trigger" arguments if the app contains no components.  This happens because the serialisation objects make `component` a mandatory field, so we cannot even load the file in this case.  This could be addressed by making `component` optional, and validating that at least one component exists during the locking process (or otherwise after the initial load).  This is probably a bit of a niche case though.

Signed-off-by: itowlson <ivan.towlson@fermyon.com>

### CODE REVIEW

File: src/commands/up.rs [hunk 1]
```diff
@@ -148,32 +148,21 @@ impl UpCommand {
...
         cmd.arg("trigger")
-            .env(SPIN_WORKING_DIR, working_dir)
-            .env(SPIN_LOCKED_URL, locked_url)
             .arg(trigger_type)
-            .args(trigger_args);
+            .env(SPIN_WORKING_DIR, &working_dir);
+
+        if self.help {
+            let help_args = vec![OsString::from("--help-args-only")];
+            cmd.args(help_args);
```
Comment (lann) [inline src/commands/up.rs:160]: Can simplify since it doesn't have to match the type of `trigger_args`:

```suggestion
            cmd.arg("--help-args-only");
```

File: src/commands/up.rs [hunk 2]
```diff
@@ -199,6 +188,25 @@ impl UpCommand {
         }
     }
 
+    fn build_locked_app(
```
Comment (lann) [inline src/commands/up.rs:191]: Maybe?

```suggestion
    fn write_locked_app(
```

**Review by lann — APPROVED** [review]
Minor style suggestions
