### PR TITLE
fix(deploy): use absolute path to load component source

### LINKED ISSUE #590: Deploy: uninformative error if run from another directory
```
~/github/fermyon-installer/aws/terraform [main|✔]
12:16 $ ls ~/github/spin/examples/http-rust/
Cargo.lock  Cargo.toml  spin.toml  src  target
~/github/fermyon-installer/aws/terraform [main|✔]
12:17 $ ~/github/spin/target/debug/spin deploy -f ~/github/spin/examples/http-rust/spin.toml
Error: No such file or directory (os error 2)
```

I added some logging and the issue appears to be that it is using the relative path to the module source from the `spin.toml` and trying to resolve it relative to the _current_ directory rather than the application directory.  As I was in the terraform directory, this didn't work.

However, it was hard to diagnose the underlying issue because the error message didn't say _which_ file or directory was missing.  This is a vexing habit of the Rust stdlib!

### PR DESCRIPTION
**Pull request by FrankYang0529**
fixes #590

### CODE REVIEW

**Review by michelleN — APPROVED** [review]
Thank you @FrankYang0529 for fixing this bug. Manually tested. Also was nice to see the `push` method on `PathBuf` being used. I usually use `join` on `Path` so I got to learn something new. 🎉 

We might also want to absolutize the app dir reference as a follow up.

Would you mind also signing your commit so we can merge?

**Comment by michelleN** [comment]
@FrankYang0529  https://spin.fermyon.dev/contributing/

**Comment by FrankYang0529** [comment]
> We might also want to absolutize the app dir reference as a follow up.

Do you mean also put app_folder in `DeployCommand`? If yes, I can help to do the follow up.

> Would you mind also signing your commit so we can merge?

I sign it. Thank you.

File: src/commands/deploy.rs [hunk 1]
```diff
@@ -200,11 +200,15 @@ impl DeployCommand {
...
     async fn compute_buildinfo(&self, cfg: &RawAppManifest) -> Result<BuildMetadata> {
         let mut sha256 = Sha256::new();
+        let mut app_folder = PathBuf::from(&self.app);
+        app_folder.pop();
 
         for x in cfg.components.iter() {
             match &x.source {
                 config::RawModuleSource::FileReference(p) => {
-                    let mut r = File::open(p)?;
+                    let mut absolute_path = PathBuf::from(&app_folder);
```
Comment (itowlson) [inline src/commands/deploy.rs:209]: Nit: this isn't necessarily an absolute path.  `full_path` maybe?

File: src/commands/deploy.rs [hunk 2]
```diff
@@ -200,11 +200,15 @@ impl DeployCommand {
...
+                    absolute_path.push(p);
```
Comment (itowlson) [inline src/commands/deploy.rs:210]: Nit: rather than separately creating a `PathBuf` and appending to it, consider `let full_path = app_folder.join(p);`

File: src/commands/deploy.rs [hunk 3]
```diff
@@ -200,11 +200,15 @@ impl DeployCommand {
...
+                    let mut r = File::open(absolute_path)?;
```
Comment (itowlson) [inline src/commands/deploy.rs:211]: Please add a `with_context`, specifically to include the file name - that way the user gets a more informative error message if anything goes wrong - unfortunately the stdlib errors are a bit woeful for this.

File: src/commands/deploy.rs [hunk 4]
```diff
@@ -200,11 +200,15 @@ impl DeployCommand {
 
     async fn compute_buildinfo(&self, cfg: &RawAppManifest) -> Result<BuildMetadata> {
         let mut sha256 = Sha256::new();
+        let mut app_folder = PathBuf::from(&self.app);
+        app_folder.pop();
```
Comment (itowlson) [inline src/commands/deploy.rs:204]: Super nit: elsewhere we have used `parent()` for this to avoid the two-step and to pick up edge case errors (e.g. `let app_folder = &self.app.parent().with_context(...)?;`.

**Review by itowlson — CHANGES_REQUESTED** [review]
This looks good - thanks!  Comments are mostly minor nits; the only important thing is that when we try to open a file it's really important to provide a `with_context` with the file name because the stdlib error gives you _no clue at all_ which file the operation has failed on - this was the issue I hit in #590!  Thanks again!

File: src/commands/deploy.rs (hunk 1 above)
Comment (FrankYang0529) [reply src/commands/deploy.rs]: Updated it. Thank you.

File: src/commands/deploy.rs (hunk 2 above)
Comment (FrankYang0529) [reply src/commands/deploy.rs]: Updated it. Thank you.

File: src/commands/deploy.rs (hunk 3 above)
Comment (FrankYang0529) [reply src/commands/deploy.rs]: Updated it. Thanks for the suggestion! I am new to Rust and I was wondering how to show error messages with more content. I know how to do it now 👍

File: src/commands/deploy.rs (hunk 4 above)
Comment (FrankYang0529) [reply src/commands/deploy.rs]: Updated it. Thank you.

**Review by itowlson — APPROVED** [review]
LGTM - thanks for the fixes!
