### PR TITLE
Dynamically detect support for Wasmtime's pooling allocator

### LINKED ISSUE #2119: On arm64, I get "cannot allocate memory (os error 12)" on executing spin up command
This is regarding the quickstart from the docs.
It runs on my X86 laptops just fine. But on arm64 platforms such as Raspberry Pi 3 (1 gb ram) or Arm based EC2 instances(with 2 GB ram), `spin build` works without any issues but on `spin up` I get the following error:

```
Error: failed to create stack pool mapping
caused by:
0: mmap failed to allocate 0x7d3e8888 bytes
1: Cannot allocate memory (os error 12)
```

Am I low on ram ? do I need more for Arm ?
Image attached. 
Screenshot (20)

### LINKED ISSUE #2343: Disable pooling allocator automatically in environments where it will fail
There are (at least) two environments where the Wasmtime pooling allocator is known to fail with Spin's default settings:

QEMU: https://github.com/fermyon/spin/issues/1785
Systems with <2GB (?) RAM:  https://github.com/fermyon/spin/issues/2119

Under `spin up` we should try to detect either of these environments and disable pooling (with a message) to improve UX.

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit is intended to address #2119 and mirror bytecodealliance/wasmtime#8610. The base problem is that some systems are configured with smaller amounts of virtual memory than other systems, for example some aarch64 and riscv64 systems are shown to have only 39 bits of virtual address space rather than the 48 by default on x86_64. This means that the pooling allocator can't be initialized on these platforms since it needs more virtual memory than that.

This changes Spin to dynamically choosing whether to use the pooling allocator. It's still used by default in Wasmtime but a dynamic probe is performed to determine whether it's going to work first. While here I also added an env var to control this behavior for an escape hatch if that's needed in the future too.

Closes #2119
Closes #2343

### CODE REVIEW

**Review by lann — APPROVED** [review]

**Comment by lann** [comment]
Also fixes #2343

File: crates/core/src/lib.rs [hunk 1]
```diff
@@ -142,6 +145,57 @@ impl Default for Config {
...
+fn use_pooling_allocator_by_default() -> bool {
+    static USE_POOLING: OnceLock<bool> = OnceLock::new();
+    const BITS_TO_TEST: u32 = 42;
+
+    *USE_POOLING.get_or_init(|| {
+        // Enable manual control through env vars as an escape hatch
+        match std::env::var("SPIN_WASMTIME_POOLING") {
+            Ok(s) if s == "1" => return true,
+            Ok(s) if s == "0" => return false,
+            _ => {}
```
Comment (rylev) [inline crates/core/src/lib.rs:178]: I think we should respect `SPIN_WASMTIME_POOLING` if it's set no matter what. If it's set to "0" or "false", we can turn it off, and otherwise enable it.

File: crates/core/src/lib.rs [hunk 2]
```diff
@@ -142,6 +145,57 @@ impl Default for Config {
...
+        // If the env var isn't set then perform the dynamic runtime probe
+        let mut config = wasmtime::Config::new();
+        config.wasm_memory64(true);
+        config.static_memory_maximum_size(1 << BITS_TO_TEST);
+
+        match wasmtime::Engine::new(&config) {
+            Ok(engine) => {
+                let mut store = wasmtime::Store::new(&engine, ());
+                // NB: the maximum size is in wasm pages to take out the 16-bits of
+                // wasm page size here from the maximum size.
```
Comment (rylev) [inline crates/core/src/lib.rs:190]: I think there is a typo here?
```suggestion
                // NB: the maximum size is in wasm pages so take out the 16-bits of
                // wasm page size here from the maximum size.
```

File: crates/core/src/lib.rs [hunk 3]
```diff
@@ -142,6 +145,57 @@ impl Default for Config {
...
+                let ty = wasmtime::MemoryType::new64(0, Some(1 << (BITS_TO_TEST - 16)));
+                wasmtime::Memory::new(&mut store, ty).is_ok()
+            }
+            Err(_) => false,
+        }
```
Comment (rylev) [inline crates/core/src/lib.rs:195]: I think we'll want to log the response here perhaps at `debug` level.

File: crates/core/src/lib.rs (hunk 1 above)
Comment (alexcrichton) [reply crates/core/src/lib.rs]: Sure yeah, I opted to panic for non 0/1 values to avoid making this too too sprawling (as it's probably not going to be used that much anyway)

**Review by rylev — APPROVED** [review]
