### PR TITLE
Fix Windows not copying globs or directories

### LINKED ISSUE #2111: Asset directory mounts do not work on Windows
The was reported by freaky.ashes on Discord - thanks to them for flagging it.

To reproduce:

* Create a Spin app with an asset directory mount (e.g. `files = [{ source = "assets", destination = "/" }]`)
* Run it on Windows
* You get a "couldn't resolve <temp>\assets\<component>" error for the component asset directory, because the assets directory didn't get created

This happens because of a conflict between canonicalisation and the glob crate: when a glob is prefixed with a canonical (UNC) path, it _does not match any files_.  (And asset directories get created only when files exist to be copied into them.)  To reproduce this, create this Rust app:

```rust
use std::path::PathBuf;

fn main() {
    println!("Using plain dir");
    let bp = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let paths = glob::glob(bp.join("src/**/*").to_str().unwrap()).unwrap();
    for path in paths {
        println!("{path:?}");
    }

    println!("Using canonicalised dir");
    let bp = PathBuf::from(env!("CARGO_MANIFEST_DIR")).canonicalize().unwrap();
    let paths = glob::glob(bp.join("src/**/*").to_str().unwrap()).unwrap();
    for path in paths {
        println!("{path:?}");
    }
}
```

It prints something like

```
Using plain dir
Ok("D:\\Code Experiments\\globtest\\src\\main.rs")
Using canonicalised dir
```

This breaks directory mounts on Spin 2 because we canonicalise the source path, and use `<source-path>/**/*` to implement directory copying.  I assume it also breaks glob mounts too but have not tested that case.

This is a known bug in the upstream glob crate: https://github.com/rust-lang/glob/issues/132.  The issue suggests a workaround which, although unsafe for general use, should be fine for us.  Alternatively it might suffice to absolutise rather than canonicalise.  The issue is 6 months old and there's no movement on it so we should not expect a fix from upstream.

### PR DESCRIPTION
**Pull request by itowlson**
Fixes #2111,

An alternative approach would be to remove the UNC prefix as mentioned in https://github.com/rust-lang/glob/issues/132, which I can implement if people prefer.

### CODE REVIEW

File: crates/loader/src/local.rs [hunk 1]
```diff
@@ -2,6 +2,7 @@ use std::path::{Path, PathBuf};
 
 use anyhow::{bail, ensure, Context, Result};
 use futures::future::try_join_all;
+use path_absolutize::Absolutize;
```
Comment (karthik2804) [inline crates/loader/src/local.rs:5]: should this also be gated to be required only on windows?

File: crates/loader/src/local.rs [hunk 2]
```diff
@@ -390,6 +389,17 @@ impl LocalLoader {
     }
 }
 
+#[cfg(not(windows))]
+fn safe_canonicalize(path: &Path) -> std::io::Result<PathBuf> {
```
Comment (rylev) [inline crates/loader/src/local.rs:393]: Can we add docs to one of these functions so there's a bit more context on why this is needed?

**Review by rylev — DISMISSED** [review]

**Comment by itowlson** [comment]
@rylev This is still blocked - I would like to get it into 2.1 if we can - do you still have concerns?

**Review by vdice — APPROVED** [review]
